In [94]:
import pandas as pd
pd.set_option("display.max_rows", 20)
pd.set_option("display.max_columns", None)
import numpy as np
import dask.dataframe as dd

In [57]:
df_dept = dd.read_csv("departments.csv")
df_dept.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [58]:
print(df_dept.shape[0].compute())

21

In [59]:
df_aisles = dd.read_csv("aisles.csv")
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [60]:
print(df_aisles.shape[0].compute())

134

In [63]:
df_products = dd.read_csv("products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [64]:
print(df_products.shape[0].compute())

49688

In [66]:
df_product_details = (
    df_products
    .merge(df_aisles, on='aisle_id', how='inner')
    .merge(df_dept, on='department_id', how='inner')
)

In [68]:
print(df_product_details.shape[0].compute())

49688

In [69]:
df_product_details.head()

,product_id,product_name,aisle_id,department_id,aisle,department
0,1,Chocolate Sandwich Cookies,61,19,cookies cakes,snacks
1,2,All-Seasons Salt,104,13,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,frozen meals,frozen
4,5,Green Chile Anytime Sauce,5,13,marinades meat preparation,pantry

In [70]:
import dask.dataframe as dd

In [71]:
df_product_details = df_product_details.drop(columns=['aisle_id', 'department_id'])

In [72]:
df_product_details = df_product_details.drop_duplicates()
df_product_details = df_product_details.dropna()

In [73]:
print(df_product_details.shape[0].compute())

49688

In [74]:
df_order_products_prior = dd.read_csv("order_products__prior.csv")

In [75]:
df_order_products_train = dd.read_csv("order_products__train.csv")

In [76]:
df_order_products = dd.concat([df_order_products_prior, df_order_products_train]).drop_duplicates()
df_order_products.head()

    order_id  product_id  add_to_cart_order  reordered
0          2       33120                  1          1
2          2        9327                  3          0
9          3       33754                  1          1
12         3       21903                  4          1
17         4       46842                  1          0

In [77]:
print(df_order_products.shape[0].compute())

11160636

In [79]:
df_orders = dd.read_csv("orders.csv")
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [80]:
print(df_orders.shape[0].compute())

3421083

In [81]:
df_order_details = (
    df_orders
    .merge(df_order_products, on='order_id', how='inner')
)
df_order_details.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,473747,1,prior,3,3,12,21.0,10258,3,1
1,473747,1,prior,3,3,12,21.0,25133,4,0
2,473747,1,prior,3,3,12,21.0,30450,5,0
3,431534,1,prior,5,4,15,28.0,196,1,1
4,431534,1,prior,5,4,15,28.0,12427,2,1

In [82]:
print(df_order_details.shape[0].compute())

11160636

In [83]:
df_order_product_details = (
    df_order_details
    .merge(df_product_details, on='product_id', how='inner')
)
df_order_product_details.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle,department
0,473747,1,prior,3,3,12,21.0,10258,3,1,Pistachios,nuts seeds dried fruit,snacks
1,473747,1,prior,3,3,12,21.0,25133,4,0,Organic String Cheese,packaged cheese,dairy eggs
2,473747,1,prior,3,3,12,21.0,30450,5,0,Creamy Almond Butter,spreads,pantry
3,431534,1,prior,5,4,15,28.0,196,1,1,Soda,soft drinks,beverages
4,431534,1,prior,5,4,15,28.0,12427,2,1,Original Beef Jerky,popcorn jerky,snacks

In [89]:
print(df_order_product_details.shape[0].compute())

11160636

In [85]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [86]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [87]:
import os

# Path to new folder
export_folder = "/content/drive/MyDrive/IIM_WPBA/exported_files"

# Create folder if it doesn't exist
os.makedirs(export_folder, exist_ok=True)

In [88]:
df_order_product_details.compute().to_csv(f"{export_folder}/full_file.csv", index=False)

In [95]:
from google.colab import drive
drive.flush_and_unmount()

In [96]:
df_full_file = dd.read_csv("full_file.csv")

In [97]:
print(df_full_file.shape[0].compute())

11160636